name: vcpkg

on:
  push:
    branches:
      - "vcpkg-test"

jobs:
  windows:
    runs-on: windows-2022
    timeout-minutes: 8
    name: vcpkg-test
    steps:
      - uses: actions/checkout@v2

      - name: switch vcpkg branch
        shell: pwsh
        run: |
          cd $env:VCPKG_INSTALLATION_ROOT
          git remote add fork https://github.com/kylo252/vcpkg
          git fetch --all
          git switch add-tree-sitter

      - name: test vcpkg
        shell: pwsh
        run: |
          vcpkg version
          vcpkg search tree-sitter

      - name: install ts
        shell: pwsh
        run: |
          vcpkg install tree-sitter:x64-windows --debug

      - name: cmake trial
        shell: pwsh
        run: |
          $vsPath = vswhere.exe -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation
          cmake -LA -S . --preset=win-x64
